services:
  django:
    build: .
    container_name: Chat
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Chat

    ports:
      - "8000:8000"


  ChatDB:
    image: postgres
    environment:
      - POSTGRES_DB=Chat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    container_name: ChatDB
    volumes:
      - ChatDBData:/var/lib/postgresql

volumes:
  ChatDBData: null