# Generated by Django 6.0.4 on 2026-04-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('Password', models.CharField()),
                ('ConfirmPassword', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField()),
                ('Task_Descriptions', models.CharField()),
                ('Task_Time', models.CharField()),
                ('Person', models.CharField()),
            ],
        ),
    ]
