# Generated by Django 6.0.3 on 2026-03-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pOne', models.CharField()),
                ('pTwo', models.CharField()),
                ('Url', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemsThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pOne', models.CharField()),
                ('pTwo', models.CharField()),
                ('Url', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemsTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pOne', models.CharField()),
                ('pTwo', models.CharField()),
                ('Url', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='InvItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pOne', models.CharField()),
                ('pTwo', models.CharField()),
                ('Url', models.CharField()),
                ('Name', models.CharField()),
            ],
        ),
    ]
