services:
  django:
    build: .
    container_name: ToDoList
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ToDoList

    ports:
      - "8000:8000"



  ToDoListDB:
    image: postgres
    environment:
      - POSTGRES_DB=ToDoList
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    container_name: ToDoListDB
    volumes:
      - DataToDoListDB:/var/lib/postgresql

volumes:
  DataToDoListDB: null