services:
  django:
    build: .
    container_name: Cases
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/Cases
    ports:
      - "8000:8000"


  CasesDB:
      image: postgres
      environment:
        - POSTGRES_DB=Case
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=12345
      container_name: CasesDB
      volumes:
        - CasesDBData:/var/lib/postgres

volumes:
  CasesDBData: null